name: brazilian_locations
description: "Flutter package to display list of States and Cities from Brazil."
version: 3.3.2
homepage: https://github.com/GuiQueirozRibeiro/brazilian_locations

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.4.3"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  http: ^1.2.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.brazilian_locations.brazilian_locations
        pluginClass: BrazilianLocationsPlugin
      ios:
        pluginClass: BrazilianLocationsPlugin
      linux:
        pluginClass: BrazilianLocationsPlugin
      macos:
        pluginClass: BrazilianLocationsPlugin
      windows:
        pluginClass: BrazilianLocationsPlugin
      web:
        pluginClass: BrazilianLocationsWeb
        fileName: brazilian_locations_web.dart
