name: brazilian_locations
description: "Flutter package to display list of States and Cities from Brazil."
version: 3.0.0
homepage: https://github.com/GuiQueirozRibeiro/brazilian_locations

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3s

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - lib/assets/

  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
