name: brazilian_locations
description: "Flutter package to display list of States and Cities from Brazil."
version: 3.1.4
homepage: https://github.com/GuiQueirozRibeiro/brazilian_locations

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - lib/assets/

  plugin:
    platforms:
      android:
        package: com.brazilian_locations.brazilian_locations
        pluginClass: BrazilianLocationsPlugin
      ios:
        pluginClass: BrazilianLocationsPlugin
      linux:
        pluginClass: BrazilianLocationsPlugin
      macos:
        pluginClass: BrazilianLocationsPlugin
      windows:
        pluginClass: BrazilianLocationsPlugin
      web:
        pluginClass: BrazilianLocationsWeb
        fileName: brazilian_locations_web.dart