name: brazilian_locations
description: "Flutter package to display list of States and Cities from Brazil."
version: 1.0.0
homepage: https://github.com/GuiQueirozRibeiro/brazilian_locations

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
